# Site Settings
title: ML_Blog
email: erfan.basiri.azad@gmail.com
description: >
  A twisted and dynamic path to becoming a Machine Learning guru.
baseurl: ""
url: "http://erfi.github.io"
twitter_username: erfi
github_username:  erfi
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  Bartos:
    output: true