# Site Settings
title: ML_Blog
email: taniarascia@gmail.com
description: >
  A twisted and dynamic path to becoming a Machine Learning guru.
baseurl: ""
url: "http://localhost:4000"
twitter_username: erfi
github_username:  erfi
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM